import os
import re

res_dir = os.path.dirname(os.path.abspath(__file__))

translations = {
    "vi": {
        "lock_biometric_title": "Mở khoá ghi chú",
        "lock_biometric_prompt_message": "Xác thực để xem hoặc chỉnh sửa ghi chú này",
        "lock_biometric_not_configured_warning": "Màn hình khoá bảo mật chưa được cài đặt trên thiết bị này",
        "action_lock_note": "Khoá ghi chú",
        "action_unlock_note": "Mở khoá ghi chú",
        "time_travel_menu_title": "Lịch sử ghi chú",
        "time_travel_title_no_versions": "Lịch sử (Chưa có phiên bản cũ)",
        "time_travel_title_version_format": "Lịch sử (Phiên bản %1$d/%2$d)",
        "time_travel_no_history": "Không có lịch sử cho ghi chú này",
        "time_travel_btn_cancel": "Hủy",
        "time_travel_btn_restore": "Khôi phục",
        "export_menu_clicked": "Đã bấm xuất ghi chú!",
        "export_dialog_title": "Xuất Ghi Chú",
        "export_as_pdf": "Xuất dưới dạng PDF",
        "export_as_image": "Xuất dưới dạng Ảnh (PNG)",
        "exporting_pdf": "Đang xuất PDF...",
        "exporting_image": "Đang xuất Ảnh...",
        "export_untitled": "Chưa đặt tên",
        "export_success_format": "Đã tạo tệp! Kích thước: %1$d bytes. Đang chia sẻ...",
        "export_share_title": "Chia sẻ ghi chú đã xuất",
        "export_failed_format": "Xuất ghi chú thất bại: %1$s"
    },
    "zh": {
        "lock_biometric_title": "解锁笔记",
        "lock_biometric_prompt_message": "验证以查看或编辑此笔记",
        "lock_biometric_not_configured_warning": "此设备未配置安全锁定屏幕",
        "action_lock_note": "锁定笔记",
        "action_unlock_note": "解锁笔记",
        "time_travel_menu_title": "历史记录",
        "time_travel_title_no_versions": "历史记录 (无旧版本)",
        "time_travel_title_version_format": "历史记录 (版本 %1$d/%2$d)",
        "time_travel_no_history": "此笔记没有历史记录",
        "time_travel_btn_cancel": "取消",
        "time_travel_btn_restore": "恢复",
        "export_menu_clicked": "已点击导出菜单！",
        "export_dialog_title": "导出笔记",
        "export_as_pdf": "导出为 PDF",
        "export_as_image": "导出为图片 (PNG)",
        "exporting_pdf": "正在导出 PDF...",
        "exporting_image": "正在导出图片...",
        "export_untitled": "无标题",
        "export_success_format": "文件已生成！大小：%1$d 字节。正在分享...",
        "export_share_title": "分享导出的笔记",
        "export_failed_format": "导出失败：%1$s"
    },
    "es": {
        "lock_biometric_title": "Desbloquear nota",
        "lock_biometric_prompt_message": "Autentíquese para ver o editar esta nota",
        "lock_biometric_not_configured_warning": "Pantalla de bloqueo de seguridad no configurada en este dispositivo",
        "action_lock_note": "Bloquear nota",
        "action_unlock_note": "Desbloquear nota",
        "time_travel_menu_title": "Historial de notas",
        "time_travel_title_no_versions": "Historial (Sin versiones anteriores)",
        "time_travel_title_version_format": "Historial (Versión %1$d/%2$d)",
        "time_travel_no_history": "No hay historial disponible para esta nota",
        "time_travel_btn_cancel": "Cancelar",
        "time_travel_btn_restore": "Restaurar",
        "export_menu_clicked": "¡Menú de exportación pulsado!",
        "export_dialog_title": "Exportar nota",
        "export_as_pdf": "Exportar como PDF",
        "export_as_image": "Exportar como imagen (PNG)",
        "exporting_pdf": "Exportando PDF...",
        "exporting_image": "Exportando imagen...",
        "export_untitled": "Sin título",
        "export_success_format": "¡Archivo generado! Tamaño: %1$d bytes. Compartiendo...",
        "export_share_title": "Compartir nota exportada",
        "export_failed_format": "Error al exportar: %1$s"
    },
    "fr": {
        "lock_biometric_title": "Déverrouiller la note",
        "lock_biometric_prompt_message": "Authentifiez-vous pour afficher ou modifier cette note",
        "lock_biometric_not_configured_warning": "Écran de verrouillage de sécurité non configuré sur cet appareil",
        "action_lock_note": "Verrouiller la note",
        "action_unlock_note": "Déverrouiller la note",
        "time_travel_menu_title": "Historique de la note",
        "time_travel_title_no_versions": "Historique (Aucune version précédente)",
        "time_travel_title_version_format": "Historique (Version %1$d/%2$d)",
        "time_travel_no_history": "Aucun historique disponible pour cette note",
        "time_travel_btn_cancel": "Annuler",
        "time_travel_btn_restore": "Restaurer",
        "export_menu_clicked": "Menu d'exportation cliqué !",
        "export_dialog_title": "Exporter la note",
        "export_as_pdf": "Exporter en PDF",
        "export_as_image": "Exporter en image (PNG)",
        "exporting_pdf": "Exportation du PDF...",
        "exporting_image": "Exportation de l'image...",
        "export_untitled": "Sans titre",
        "export_success_format": "Fichier généré ! Taille : %1$d octets. Partage...",
        "export_share_title": "Partager la note exportée",
        "export_failed_format": "Échec de l'exportation : %1$s"
    },
    "de": {
        "lock_biometric_title": "Notiz entsperren",
        "lock_biometric_prompt_message": "Authentifizieren Sie sich, um diese Notiz anzuzeigen oder zu bearbeiten",
        "lock_biometric_not_configured_warning": "Sicherheitssperrbildschirm auf diesem Gerät nicht konfiguriert",
        "action_lock_note": "Notiz sperren",
        "action_unlock_note": "Notiz entsperren",
        "time_travel_menu_title": "Versionsverlauf",
        "time_travel_title_no_versions": "Verlauf (Keine früheren Versionen)",
        "time_travel_title_version_format": "Verlauf (Version %1$d/%2$d)",
        "time_travel_no_history": "Kein Verlauf für diese Notiz verfügbar",
        "time_travel_btn_cancel": "Abbrechen",
        "time_travel_btn_restore": "Wiederherstellen",
        "export_menu_clicked": "Export-Menü geklickt!",
        "export_dialog_title": "Notiz exportieren",
        "export_as_pdf": "Als PDF exportieren",
        "export_as_image": "Als Bild (PNG) exportieren",
        "exporting_pdf": "Exportiere PDF...",
        "exporting_image": "Exportiere Bild...",
        "export_untitled": "Unbenannt",
        "export_success_format": "Datei erstellt! Größe: %1$d Bytes. Teilen...",
        "export_share_title": "Exportierte Notiz teilen",
        "export_failed_format": "Export fehlgeschlagen: %1$s"
    },
    "ja": {
        "lock_biometric_title": "メモをロック解除",
        "lock_biometric_prompt_message": "このメモを表示または編集するには認証してください",
        "lock_biometric_not_configured_warning": "このデバイスでセキュリティロック画面が設定されていません",
        "action_lock_note": "メモをロック",
        "action_unlock_note": "メモをロック解除",
        "time_travel_menu_title": "変更履歴",
        "time_travel_title_no_versions": "履歴 (以前のバージョンはありません)",
        "time_travel_title_version_format": "履歴 (バージョン %1$d/%2$d)",
        "time_travel_no_history": "このメモの履歴はありません",
        "time_travel_btn_cancel": "キャンセル",
        "time_travel_btn_restore": "復元",
        "export_menu_clicked": "エクスポートメニューがクリックされました！",
        "export_dialog_title": "メモのエクスポート",
        "export_as_pdf": "PDFとしてエクスポート",
        "export_as_image": "画像 (PNG) としてエクスポート",
        "exporting_pdf": "PDFをエクスポート中...",
        "exporting_image": "画像をエクスポート中...",
        "export_untitled": "無題",
        "export_success_format": "ファイルが生成されました！サイズ：%1$d 局。共有中...",
        "export_share_title": "エクスポートされたメモを共有",
        "export_failed_format": "エクスポートに失敗しました：%1$s"
    },
    "ko": {
        "lock_biometric_title": "메모 잠금 해제",
        "lock_biometric_prompt_message": "이 메모를 보거나 편집하려면 인증하세요",
        "lock_biometric_not_configured_warning": "이 기기에 보안 잠금 화면이 구성되어 있지 않습니다",
        "action_lock_note": "메모 잠금",
        "action_unlock_note": "메모 잠금 해제",
        "time_travel_menu_title": "변경 이력",
        "time_travel_title_no_versions": "이력 (이전 버전 없음)",
        "time_travel_title_version_format": "이력 (버전 %1$d/%2$d)",
        "time_travel_no_history": "이 메모에 대한 이력이 없습니다",
        "time_travel_btn_cancel": "취소",
        "time_travel_btn_restore": "복원",
        "export_menu_clicked": "내보내기 메뉴를 클릭했습니다!",
        "export_dialog_title": "메모 내보내기",
        "export_as_pdf": "PDF로 내보내기",
        "export_as_image": "이미지 (PNG)로 내보내기",
        "exporting_pdf": "PDF 내보내는 중...",
        "exporting_image": "이미지 내보내는 중...",
        "export_untitled": "제목 없음",
        "export_success_format": "파일이 생성되었습니다! 크기: %1$d 바이트. 공유 중...",
        "export_share_title": "내보낸 메모 공유",
        "export_failed_format": "내보내기 실패: %1$s"
    },
    "ru": {
        "lock_biometric_title": "Разблокировать заметку",
        "lock_biometric_prompt_message": "Авторизуйтесь, чтобы просмотреть или отредактировать заметку",
        "lock_biometric_not_configured_warning": "Экран блокировки не настроен на этом устройстве",
        "action_lock_note": "Заблокировать заметку",
        "action_unlock_note": "Разблокировать заметку",
        "time_travel_menu_title": "История изменений",
        "time_travel_title_no_versions": "История (Нет предыдущих версий)",
        "time_travel_title_version_format": "История (Версия %1$d/%2$d)",
        "time_travel_no_history": "История для этой заметки отсутствует",
        "time_travel_btn_cancel": "Отмена",
        "time_travel_btn_restore": "Восстановить",
        "export_menu_clicked": "Нажато меню экспорта!",
        "export_dialog_title": "Экспорт заметки",
        "export_as_pdf": "Экспорт в PDF",
        "export_as_image": "Экспорт в изображение (PNG)",
        "exporting_pdf": "Экспорт PDF...",
        "exporting_image": "Экспорт изображения...",
        "export_untitled": "Без названия",
        "export_success_format": "Файл создан! Размер: %1$d байт. Отправка...",
        "export_share_title": "Поделиться экспортированной заметкой",
        "export_failed_format": "Ошибка экспорта: %1$s"
    },
    "pt": {
        "lock_biometric_title": "Desbloquear nota",
        "lock_biometric_prompt_message": "Autentique-se para visualizar ou editar esta nota",
        "lock_biometric_not_configured_warning": "Tela de bloqueio de segurança não configurada neste dispositivo",
        "action_lock_note": "Bloquear nota",
        "action_unlock_note": "Desbloquear nota",
        "time_travel_menu_title": "Histórico de notas",
        "time_travel_title_no_versions": "Histórico (Sem versões anteriores)",
        "time_travel_title_version_format": "Histórico (Versão %1$d/%2$d)",
        "time_travel_no_history": "Nenhum histórico disponível para esta nota",
        "time_travel_btn_cancel": "Cancelar",
        "time_travel_btn_restore": "Restaurar",
        "export_menu_clicked": "Menu de exportação clicado!",
        "export_dialog_title": "Exportar nota",
        "export_as_pdf": "Exportar como PDF",
        "export_as_image": "Exportar como imagem (PNG)",
        "exporting_pdf": "Exportando PDF...",
        "exporting_image": "Exportando imagem...",
        "export_untitled": "Sem título",
        "export_success_format": "Arquivo gerado! Tamanho: %1$d bytes. Compartilhando...",
        "export_share_title": "Compartilhar nota exportada",
        "export_failed_format": "Falha ao exportar: %1$s"
    },
    "it": {
        "lock_biometric_title": "Sblocca nota",
        "lock_biometric_prompt_message": "Autenticati per visualizzare o modificare questa nota",
        "lock_biometric_not_configured_warning": "Schermo di blocco di sicurezza non configurato su questo dispositivo",
        "action_lock_note": "Blocca nota",
        "action_unlock_note": "Sblocca nota",
        "time_travel_menu_title": "Cronologia modifiche",
        "time_travel_title_no_versions": "Cronologia (Nessuna versione precedente)",
        "time_travel_title_version_format": "Cronologia (Versione %1$d/%2$d)",
        "time_travel_no_history": "Nessuna cronologia disponibile per questa nota",
        "time_travel_btn_cancel": "Annulla",
        "time_travel_btn_restore": "Ripristina",
        "export_menu_clicked": "Menu esportazione cliccato!",
        "export_dialog_title": "Esporta nota",
        "export_as_pdf": "Esporta come PDF",
        "export_as_image": "Esporta come immagine (PNG)",
        "exporting_pdf": "Esportazione in PDF...",
        "exporting_image": "Esportazione dell'immagine...",
        "export_untitled": "Senza titolo",
        "export_success_format": "File generato! Dimensione: %1$d byte. Condivisione...",
        "export_share_title": "Condividi nota esportata",
        "export_failed_format": "Esportazione non riuscita: %1$s"
    },
    "ar": {
        "lock_biometric_title": "إلغاء قفل الملاحظة",
        "lock_biometric_prompt_message": "الرجاء التحقق لعرض أو تعديل هذه الملاحظة",
        "lock_biometric_not_configured_warning": "قفل الشاشة غير مفعّل على هذا الجهاز",
        "action_lock_note": "قفل الملاحظة",
        "action_unlock_note": "إلغاء قفل الملاحظة",
        "time_travel_menu_title": "سجل الملاحظة",
        "time_travel_title_no_versions": "السجل (لا توجد إصدارات سابقة)",
        "time_travel_title_version_format": "السجل (إصدار %1$d/%2$d)",
        "time_travel_no_history": "لا يوجد سجل متاح لهذه الملاحظة",
        "time_travel_btn_cancel": "إلغاء",
        "time_travel_btn_restore": "استعادة",
        "export_menu_clicked": "تم النقر على قائمة التصدير!",
        "export_dialog_title": "تصدير الملاحظة",
        "export_as_pdf": "تصدير كـ PDF",
        "export_as_image": "تصدير كصورة (PNG)",
        "exporting_pdf": "جاري تصدير PDF...",
        "exporting_image": "جاري تصدير الصورة...",
        "export_untitled": "بدون عنوان",
        "export_success_format": "تم إنشاء الملف! الحجم: %1$d بايت. جاري المشاركة...",
        "export_share_title": "مشاركة الملاحظة المصدرة",
        "export_failed_format": "فشل التصدير: %1$s"
    },
    "hi": {
        "lock_biometric_title": "नोट अनलॉक करें",
        "lock_biometric_prompt_message": "इस नोट को देखने या संपादित करने के लिए प्रमाणित करें",
        "lock_biometric_not_configured_warning": "इस डिवाइस पर सुरक्षा लॉक स्क्रीन कॉन्फ़िगर नहीं की गई है",
        "action_lock_note": "नोट लॉक करें",
        "action_unlock_note": "नोट अनलॉक करें",
        "time_travel_menu_title": "नोट इतिहास",
        "time_travel_title_no_versions": "इतिहास (कोई पिछला संस्करण नहीं)",
        "time_travel_title_version_format": "इतिहास (संस्करण %1$d/%2$d)",
        "time_travel_no_history": "इस नोट के लिए कोई इतिहास उपलब्ध नहीं है",
        "time_travel_btn_cancel": "रद्द करें",
        "time_travel_btn_restore": "पुनर्स्थापित करें",
        "export_menu_clicked": "निर्यात मेनू पर क्लिक किया गया!",
        "export_dialog_title": "नोट निर्यात करें",
        "export_as_pdf": "PDF के रूप में निर्यात करें",
        "export_as_image": "छवि (PNG) के रूप में निर्यात करें",
        "exporting_pdf": "PDF निर्यात हो रहा है...",
        "exporting_image": "छवि निर्यात हो रही है...",
        "export_untitled": "बिना शीर्षक का",
        "export_success_format": "फ़ाइल उत्पन्न हुई! आकार: %1$d बाइट्स। साझा किया जा रहा है...",
        "export_share_title": "निर्यातित नोट साझा करें",
        "export_failed_format": "निर्यात विफल रहा: %1$s"
    },
    "id": {
        "lock_biometric_title": "Buka kunci catatan",
        "lock_biometric_prompt_message": "Lakukan autentikasi untuk melihat atau mengedit catatan ini",
        "lock_biometric_not_configured_warning": "Layar kunci keamanan tidak dikonfigurasi pada perangkat ini",
        "action_lock_note": "Kunci catatan",
        "action_unlock_note": "Buka kunci catatan",
        "time_travel_menu_title": "Riwayat catatan",
        "time_travel_title_no_versions": "Riwayat (Tidak ada versi sebelumnya)",
        "time_travel_title_version_format": "Riwayat (Versi %1$d/%2$d)",
        "time_travel_no_history": "Tidak ada riwayat untuk catatan ini",
        "time_travel_btn_cancel": "Batal",
        "time_travel_btn_restore": "Pulihkan",
        "export_menu_clicked": "Menu ekspor diklik!",
        "export_dialog_title": "Ekspor Catatan",
        "export_as_pdf": "Ekspor sebagai PDF",
        "export_as_image": "Ekspor sebagai Gambar (PNG)",
        "exporting_pdf": "Mengekspor PDF...",
        "exporting_image": "Mengekspor Gambar...",
        "export_untitled": "Tanpa judul",
        "export_success_format": "File dibuat! Ukuran: %1$d byte. Membagikan...",
        "export_share_title": "Bagikan Catatan yang Diekspor",
        "export_failed_format": "Gagal mengekspor: %1$s"
    },
    "ms": {
        "lock_biometric_title": "Buka kunci nota",
        "lock_biometric_prompt_message": "Sahkan untuk melihat atau mengedit nota ini",
        "lock_biometric_not_configured_warning": "Skrin kunci keselamatan tidak dikonfigurasikan pada peranti ini",
        "action_lock_note": "Kunci nota",
        "action_unlock_note": "Buka kunci nota",
        "time_travel_menu_title": "Sejarah nota",
        "time_travel_title_no_versions": "Sejarah (Tiada versi terdahulu)",
        "time_travel_title_version_format": "Sejarah (Versi %1$d/%2$d)",
        "time_travel_no_history": "Tiada sejarah tersedia untuk nota ini",
        "time_travel_btn_cancel": "Batal",
        "time_travel_btn_restore": "Pulihkan",
        "export_menu_clicked": "Menu eksport diklik!",
        "export_dialog_title": "Eksport Nota",
        "export_as_pdf": "Eksport sebagai PDF",
        "export_as_image": "Eksport sebagai Imej (PNG)",
        "exporting_pdf": "Mengeksport PDF...",
        "exporting_image": "Mengeksport Imej...",
        "export_untitled": "Tanpa tajuk",
        "export_success_format": "Fail dijana! Saiz: %1$d bait. Berkongsi...",
        "export_share_title": "Kongsi Nota yang Dieksport",
        "export_failed_format": "Gagal mengeksport: %1$s"
    },
    "tr": {
        "lock_biometric_title": "Notun kilidini aç",
        "lock_biometric_prompt_message": "Bu notu görüntülemek veya düzenlemek için kimlik doğrulaması yapın",
        "lock_biometric_not_configured_warning": "Güvenlik kilit ekranı bu cihazda yapılandırılmamış",
        "action_lock_note": "Notu kilitle",
        "action_unlock_note": "Notun kilidini aç",
        "time_travel_menu_title": "Not geçmişi",
        "time_travel_title_no_versions": "Geçmiş (Önceki sürüm yok)",
        "time_travel_title_version_format": "Geçmiş (Sürüm %1$d/%2$d)",
        "time_travel_no_history": "Bu not için geçmiş bulunmamaktadır",
        "time_travel_btn_cancel": "İptal",
        "time_travel_btn_restore": "Geri yükle",
        "export_menu_clicked": "Dışa aktarma menüsüne tıklandı!",
        "export_dialog_title": "Notu Dışa Aktar",
        "export_as_pdf": "PDF olarak dışa aktar",
        "export_as_image": "Resim (PNG) olarak dışa aktar",
        "exporting_pdf": "PDF dışa aktarılıyor...",
        "exporting_image": "Resim dışa aktarılıyor...",
        "export_untitled": "Başlıksız",
        "export_success_format": "Dosya oluşturuldu! Boyut: %1$d bayt. Paylaşılıyor...",
        "export_share_title": "Dışa Aktarılan Notu Paylaş",
        "export_failed_format": "Dışa aktarma başarısız: %1$s"
    },
    "th": {
        "lock_biometric_title": "ปลดล็อกโน้ต",
        "lock_biometric_prompt_message": "ยืนยันตัวตนเพื่อดูหรือแก้ไขโน้ตนี้",
        "lock_biometric_not_configured_warning": "ไม่ได้ตั้งค่าการล็อกหน้าจอความปลอดภัยบนอุปกรณ์นี้",
        "action_lock_note": "ล็อกโน้ต",
        "action_unlock_note": "ปลดล็อกโน้ต",
        "time_travel_menu_title": "ประวัติโน้ต",
        "time_travel_title_no_versions": "ประวัติ (ไม่มีเวอร์ชันก่อนหน้า)",
        "time_travel_title_version_format": "ประวัติ (เวอร์ชัน %1$d/%2$d)",
        "time_travel_no_history": "ไม่มีประวัติสำหรับโน้ตนี้",
        "time_travel_btn_cancel": "ยกเลิก",
        "time_travel_btn_restore": "กู้คืน",
        "export_menu_clicked": "คลิกเมนูส่งออกแล้ว!",
        "export_dialog_title": "ส่งออกโน้ต",
        "export_as_pdf": "ส่งออกเป็น PDF",
        "export_as_image": "ส่งออกเป็นรูปภาพ (PNG)",
        "exporting_pdf": "กำลังส่งออก PDF...",
        "exporting_image": "กำลังส่งออกรูปภาพ...",
        "export_untitled": "ไม่มีชื่อ",
        "export_success_format": "สร้างไฟล์แล้ว! ขนาด: %1$d ไบต์ กำลังแชร์...",
        "export_share_title": "แชร์โน้ตที่ส่งออก",
        "export_failed_format": "ส่งออกล้มเหลว: %1$s"
    },
    "nl": {
        "lock_biometric_title": "Notitie ontgrendelen",
        "lock_biometric_prompt_message": "Verifieer om deze notitie te bekijken of te bewerken",
        "lock_biometric_not_configured_warning": "Beveiligingsschermvergrendeling is niet geconfigureerd op dit apparaat",
        "action_lock_note": "Notitie vergrendelen",
        "action_unlock_note": "Notitie ontgrendelen",
        "time_travel_menu_title": "Notitiegeschiedenis",
        "time_travel_title_no_versions": "Geschiedenis (Geen eerdere versies)",
        "time_travel_title_version_format": "Geschiedenis (Versie %1$d/%2$d)",
        "time_travel_no_history": "Geen geschiedenis beschikbaar voor deze notitie",
        "time_travel_btn_cancel": "Annuleren",
        "time_travel_btn_restore": "Herstellen",
        "export_menu_clicked": "Exportmenu geklikt!",
        "export_dialog_title": "Notitie exporteren",
        "export_as_pdf": "Exporteren als PDF",
        "export_as_image": "Exporteren als afbeelding (PNG)",
        "exporting_pdf": "PDF exporteren...",
        "exporting_image": "Afbeelding exporteren...",
        "export_untitled": "Naamloos",
        "export_success_format": "Bestand gegenereerd! Grootte: %1$d bytes. Delen...",
        "export_share_title": "Geëxporteerde notitie delen",
        "export_failed_format": "Exporteren mislukt: %1$s"
    },
    "pl": {
        "lock_biometric_title": "Odblokuj notatkę",
        "lock_biometric_prompt_message": "Uwierzytelnij się, aby wyświetlić lub edytować notatkę",
        "lock_biometric_not_configured_warning": "Blokada ekranu zabezpieczeń nie została skonfigurowana na tym urządzeniu",
        "action_lock_note": "Zablokuj notatkę",
        "action_unlock_note": "Odblokuj notatkę",
        "time_travel_menu_title": "Historia notatki",
        "time_travel_title_no_versions": "Historia (Brak poprzednich wersji)",
        "time_travel_title_version_format": "Historia (Wersja %1$d/%2$d)",
        "time_travel_no_history": "Brak historii dla tej notatki",
        "time_travel_btn_cancel": "Anuluj",
        "time_travel_btn_restore": "Przywróć",
        "export_menu_clicked": "Kliknięto menu eksportu!",
        "export_dialog_title": "Eksportuj notatkę",
        "export_as_pdf": "Eksportuj jako PDF",
        "export_as_image": "Eksportuj jako obraz (PNG)",
        "exporting_pdf": "Eksportowanie PDF...",
        "exporting_image": "Eksportowanie obrazu...",
        "export_untitled": "Bez tytułu",
        "export_success_format": "Plik wygenerowany! Rozmiar: %1$d bajtów. Udostępnianie...",
        "export_share_title": "Udostępnij wyeksportowaną notatkę",
        "export_failed_format": "Błąd eksportu: %1$s"
    },
    "sv": {
        "lock_biometric_title": "Lås upp anteckning",
        "lock_biometric_prompt_message": "Verifiera för att visa eller redigera anteckningen",
        "lock_biometric_not_configured_warning": "Säkerhetsskärmlås har inte konfigurerats på den här enheten",
        "action_lock_note": "Lås anteckning",
        "action_unlock_note": "Lås upp anteckning",
        "time_travel_menu_title": "Anteckningshistorik",
        "time_travel_title_no_versions": "Historik (Inga tidigare versioner)",
        "time_travel_title_version_format": "Historik (Version %1$d/%2$d)",
        "time_travel_no_history": "Ingen historik tillgänglig för denna anteckning",
        "time_travel_btn_cancel": "Avbryt",
        "time_travel_btn_restore": "Återställ",
        "export_menu_clicked": "Exportmenyn klickades!",
        "export_dialog_title": "Exportera anteckning",
        "export_as_pdf": "Exportera som PDF",
        "export_as_image": "Exportera som bild (PNG)",
        "exporting_pdf": "Exporterar PDF...",
        "exporting_image": "Exporterar bild...",
        "export_untitled": "Namnlös",
        "export_success_format": "Fil skapad! Storlek: %1$d byte. Delar...",
        "export_share_title": "Dela exporterad anteckning",
        "export_failed_format": "Misslyckades att exportera: %1$s"
    },
    "da": {
        "lock_biometric_title": "Lås note op",
        "lock_biometric_prompt_message": "Godkend for at få adgang til eller redigere denne note",
        "lock_biometric_not_configured_warning": "Sikkerhedsskærmlås er ikke konfigureret på denne enhed",
        "action_lock_note": "Lås note",
        "action_unlock_note": "Lås note op",
        "time_travel_menu_title": "Notehistorik",
        "time_travel_title_no_versions": "Historik (Ingen tidligere versioner)",
        "time_travel_title_version_format": "Historik (Version %1$d/%2$d)",
        "time_travel_no_history": "Ingen historik tilgængelig for denne note",
        "time_travel_btn_cancel": "Annuller",
        "time_travel_btn_restore": "Gendan",
        "export_menu_clicked": "Eksportmenu klikket!",
        "export_dialog_title": "Eksporter note",
        "export_as_pdf": "Eksporter som PDF",
        "export_as_image": "Eksporter som billede (PNG)",
        "exporting_pdf": "Eksporterer PDF...",
        "exporting_image": "Eksporterer billede...",
        "export_untitled": "Uden titel",
        "export_success_format": "Fil genereret! Størrelse: %1$d bytes. Deler...",
        "export_share_title": "Del eksporteret note",
        "export_failed_format": "Kunne ikke eksportere: %1$s"
    },
    "fi": {
        "lock_biometric_title": "Avaa muistiinpanon lukitus",
        "lock_biometric_prompt_message": "Tunnistaudu tarkastellaksesi tai muokataksesi tätä muistiinpanoa",
        "lock_biometric_not_configured_warning": "Suojattua näytön lukitusta ei ole määritetty tällä laitteella",
        "action_lock_note": "Lukitse muistiinpano",
        "action_unlock_note": "Avaa muistiinpanon lukitus",
        "time_travel_menu_title": "Muistiinpanon historia",
        "time_travel_title_no_versions": "Historia (Ei aiempia versioita)",
        "time_travel_title_version_format": "Historia (Versio %1$d/%2$d)",
        "time_travel_no_history": "Tälle muistiinpanolle ei ole historiaa",
        "time_travel_btn_cancel": "Peruuta",
        "time_travel_btn_restore": "Palauta",
        "export_menu_clicked": "Vientivalikkoa klikattu!",
        "export_dialog_title": "Vie muistiinpano",
        "export_as_pdf": "Vie PDF-muodossa",
        "export_as_image": "Vie kuvana (PNG)",
        "exporting_pdf": "Viedään PDF-muotoon...",
        "exporting_image": "Viedään kuvaksi...",
        "export_untitled": "Nimetön",
        "export_success_format": "Tiedosto luotu! Koko: %1$d tavua. Jaetaan...",
        "export_share_title": "Jaa viety muistiinpano",
        "export_failed_format": "Vienti epäonnistui: %1$s"
    },
    "nb": {
        "lock_biometric_title": "Lås opp notat",
        "lock_biometric_prompt_message": "Autentiser for å vise eller redigere dette notatet",
        "lock_biometric_not_configured_warning": "Sikkerhetsskjermlås er ikke konfigurert på denne enheten",
        "action_lock_note": "Lås notat",
        "action_unlock_note": "Lås opp notat",
        "time_travel_menu_title": "Notathistorikk",
        "time_travel_title_no_versions": "Historikk (Ingen tidligere versjoner)",
        "time_travel_title_version_format": "Historikk (Versjon %1$d/%2$d)",
        "time_travel_no_history": "Ingen historikk tilgjengelig for dette notatet",
        "time_travel_btn_cancel": "Avbryt",
        "time_travel_btn_restore": "Gjenopprett",
        "export_menu_clicked": "Eksportmeny klikket!",
        "export_dialog_title": "Eksporter notat",
        "export_as_pdf": "Eksporter som PDF",
        "export_as_image": "Eksporter som bilde (PNG)",
        "exporting_pdf": "Eksporterer PDF...",
        "exporting_image": "Eksporterer bilde...",
        "export_untitled": "Uten tittel",
        "export_success_format": "Fil opprettet! Størrelse: %1$d byte. Deler...",
        "export_share_title": "Del eksportert notat",
        "export_failed_format": "Kunne ikke eksportere: %1$s"
    },
    "ro": {
        "lock_biometric_title": "Deblochează nota",
        "lock_biometric_prompt_message": "Autentificați-vă pentru a vizualiza sau edita această notă",
        "lock_biometric_not_configured_warning": "Ecranul de blocare de securitate nu este configurat pe acest dispozitiv",
        "action_lock_note": "Blochează nota",
        "action_unlock_note": "Deblochează nota",
        "time_travel_menu_title": "Istoricul notei",
        "time_travel_title_no_versions": "Istoric (Fără versiuni anterioare)",
        "time_travel_title_version_format": "Istoric (Versiunea %1$d/%2$d)",
        "time_travel_no_history": "Niciun istoric disponibil pentru această notă",
        "time_travel_btn_cancel": "Anulează",
        "time_travel_btn_restore": "Restaurează",
        "export_menu_clicked": "Meniu export clicat!",
        "export_dialog_title": "Exportă nota",
        "export_as_pdf": "Exportă ca PDF",
        "export_as_image": "Exportă ca imagine (PNG)",
        "exporting_pdf": "Se exportă ca PDF...",
        "exporting_image": "Se exportă ca imagine...",
        "export_untitled": "Fără titlu",
        "export_success_format": "Fișier generat! Dimensiune: %1$d octeți. Se trimite...",
        "export_share_title": "Trimite nota exportată",
        "export_failed_format": "Export eșuat: %1$s"
    },
    "bg": {
        "lock_biometric_title": "Отключване на бележка",
        "lock_biometric_prompt_message": "Удостоверете се за преглед или редактиране на тази бележка",
        "lock_biometric_not_configured_warning": "Защитното заключване на екрана не е конфигурирано на това устройство",
        "action_lock_note": "Заключване на бележка",
        "action_unlock_note": "Отключване на бележка",
        "time_travel_menu_title": "История на бележката",
        "time_travel_title_no_versions": "История (Няма предишни версии)",
        "time_travel_title_version_format": "История (Версия %1$d/%2$d)",
        "time_travel_no_history": "Няма налична история за тази бележка",
        "time_travel_btn_cancel": "Отказ",
        "time_travel_btn_restore": "Възстановяване",
        "export_menu_clicked": "Кликнато меню за експортиране!",
        "export_dialog_title": "Експортиране на бележка",
        "export_as_pdf": "Експортиране като PDF",
        "export_as_image": "Експортиране като изображение (PNG)",
        "exporting_pdf": "Експортиране на PDF...",
        "exporting_image": "Експортиране на изображение...",
        "export_untitled": "Без заглавие",
        "export_success_format": "Файлът е генериран! Размер: %1$d байта. Споделяне...",
        "export_share_title": "Споделяне на експортираната бележка",
        "export_failed_format": "Неуспешно експортиране: %1$s"
    },
    "cs": {
        "lock_biometric_title": "Odemknout poznámku",
        "lock_biometric_prompt_message": "Ověřte se pro zobrazení nebo úpravu této poznámky",
        "lock_biometric_not_configured_warning": "Zámek obrazovky zabezpečení není na tomto zařízení nakonfigurován",
        "action_lock_note": "Zamknout poznámku",
        "action_unlock_note": "Odemknout poznámku",
        "time_travel_menu_title": "Historie poznámky",
        "time_travel_title_no_versions": "Historie (Žádné předchozí verze)",
        "time_travel_title_version_format": "Historie (Verze %1$d/%2$d)",
        "time_travel_no_history": "Pro tuto poznámku není k dispozici žádná historie",
        "time_travel_btn_cancel": "Zrušit",
        "time_travel_btn_restore": "Obnovit",
        "export_menu_clicked": "Kliknuto na nabídku exportu!",
        "export_dialog_title": "Exportovat poznámku",
        "export_as_pdf": "Exportovat jako PDF",
        "export_as_image": "Exportovat jako obrázek (PNG)",
        "exporting_pdf": "Exportování PDF...",
        "exporting_image": "Exportování obrázku...",
        "export_untitled": "Bez názvu",
        "export_success_format": "Soubor vytvořen! Velikost: %1$d bajtů. Sdílení...",
        "export_share_title": "Sdílet exportovanou poznámku",
        "export_failed_format": "Export selhal: %1$s"
    },
    "sk": {
        "lock_biometric_title": "Odomknúť poznámku",
        "lock_biometric_prompt_message": "Overte sa pre zobrazenie alebo úpravu tejto poznámky",
        "lock_biometric_not_configured_warning": "Zámok obrazovky zabezpečenia nie je na tomto zariadení nakonfigurovaný",
        "action_lock_note": "Zamknúť poznámku",
        "action_unlock_note": "Odomknúť poznámku",
        "time_travel_menu_title": "História poznámky",
        "time_travel_title_no_versions": "História (Žiadne predchádzajúce verzie)",
        "time_travel_title_version_format": "História (Verzia %1$d/%2$d)",
        "time_travel_no_history": "Pre túto poznámku nie je k dispozícii žiadna história",
        "time_travel_btn_cancel": "Zrušiť",
        "time_travel_btn_restore": "Obnoviť",
        "export_menu_clicked": "Kliknuté na ponuku exportu!",
        "export_dialog_title": "Exportovať poznámku",
        "export_as_pdf": "Exportovať ako PDF",
        "export_as_image": "Exportovať ako obrázok (PNG)",
        "exporting_pdf": "Exportovanie PDF...",
        "exporting_image": "Exportovanie obrázka...",
        "export_untitled": "Bez názvu",
        "export_success_format": "Súbor vytvorený! Veľkosť: %1$d bajtov. Zdieľanie...",
        "export_share_title": "Zdieľať exportovanú poznámku",
        "export_failed_format": "Export zlyhal: %1$s"
    },
    "el": {
        "lock_biometric_title": "Ξεκλείδωμα σημείωσης",
        "lock_biometric_prompt_message": "Ταυτοποιηθείτε για να δείτε ή να επεξεργαστείτε αυτήν τη σημείωση",
        "lock_biometric_not_configured_warning": "Το κλείδωμα οθόνης δεν είναι ρυθμισμένο σε αυτήν τη συσκευή",
        "action_lock_note": "Κλείδωμα σημείωσης",
        "action_unlock_note": "Ξεκλείδωμα σημείωσης",
        "time_travel_menu_title": "Ιστορικό σημείωσης",
        "time_travel_title_no_versions": "Ιστορικό (Δεν υπάρχουν προηγούμενες εκδόσεις)",
        "time_travel_title_version_format": "Ιστορικό (Έκδοση %1$d/%2$d)",
        "time_travel_no_history": "Δεν υπάρχει διαθέσιμο ιστορικό για αυτήν τη σημείωση",
        "time_travel_btn_cancel": "Ακύρωση",
        "time_travel_btn_restore": "Επαναφορά",
        "export_menu_clicked": "Κλικ στο μενού εξαγωγής!",
        "export_dialog_title": "Εξαγωγή σημείωσης",
        "export_as_pdf": "Εξαγωγή ως PDF",
        "export_as_image": "Εξαγωγή ως εικόνα (PNG)",
        "exporting_pdf": "Εξαγωγή PDF...",
        "exporting_image": "Εξαγωγή εικόνας...",
        "export_untitled": "Χωρίς τίτλο",
        "export_success_format": "Το αρχείο δημιουργήθηκε! Μέγεθος: %1$d byte. Κοινή χρήση...",
        "export_share_title": "Κοινοποίηση εξαγόμενης σημείωσης",
        "export_failed_format": "Η εξαγωγή απέτυχε: %1$s"
    },
    "hr": {
        "lock_biometric_title": "Otključaj bilješku",
        "lock_biometric_prompt_message": "Provjerite autentičnost da biste vidjeli ili uredili ovu bilješku",
        "lock_biometric_not_configured_warning": "Zaključavanje zaslona nije konfigurirano na ovom uređaju",
        "action_lock_note": "Zaključaj bilješku",
        "action_unlock_note": "Otključaj bilješku",
        "time_travel_menu_title": "Povijest bilješke",
        "time_travel_title_no_versions": "Povijest (Nema prethodnih verzija)",
        "time_travel_title_version_format": "Povijest (Verzija %1$d/%2$d)",
        "time_travel_no_history": "Nema dostupne povijesti za ovu bilješku",
        "time_travel_btn_cancel": "Odustani",
        "time_travel_btn_restore": "Vrati",
        "export_menu_clicked": "Kliknut izbornik za izvoz!",
        "export_dialog_title": "Izvezi bilješku",
        "export_as_pdf": "Izvezi kao PDF",
        "export_as_image": "Izvezi kao sliku (PNG)",
        "exporting_pdf": "Izvoz PDF-a...",
        "exporting_image": "Izvoz slike...",
        "export_untitled": "Bez naslova",
        "export_success_format": "Datoteka stvorena! Veličina: %1$d bajtova. Dijeljenje...",
        "export_share_title": "Podijeli izvezenu bilješku",
        "export_failed_format": "Izvoz nije uspio: %1$s"
    },
    "hu": {
        "lock_biometric_title": "Jegyzet feloldása",
        "lock_biometric_prompt_message": "Hitelesítsen a jegyzet megtekintéséhez vagy szerkesztéséhez",
        "lock_biometric_not_configured_warning": "A képernyőzár biztonsága nincs beállítva ezen az eszközön",
        "action_lock_note": "Jegyzet zárolása",
        "action_unlock_note": "Jegyzet feloldása",
        "time_travel_menu_title": "Jegyzetelőzmények",
        "time_travel_title_no_versions": "Előzmények (Nincsenek korábbi verziók)",
        "time_travel_title_version_format": "Előzmények (%1$d/%2$d. verzió)",
        "time_travel_no_history": "Nincs elérhető előzmény ehhez a jegyzethez",
        "time_travel_btn_cancel": "Mégse",
        "time_travel_btn_restore": "Visszaállítás",
        "export_menu_clicked": "Exportálás menüre kattintva!",
        "export_dialog_title": "Jegyzet exportálása",
        "export_as_pdf": "Exportálás PDF-ként",
        "export_as_image": "Exportálás képként (PNG)",
        "exporting_pdf": "PDF exportálása...",
        "exporting_image": "Kép exportálása...",
        "export_untitled": "Névtelen",
        "export_success_format": "Fájl létrehozva! Méret: %1$d bájt. Megosztás...",
        "export_share_title": "Exportált jegyzet megosztása",
        "export_failed_format": "Exportálás sikertelen: %1$s"
    },
    "uk": {
        "lock_biometric_title": "Розблокувати замітку",
        "lock_biometric_prompt_message": "Автентифікуйтеся, щоб переглянути або змінити цю замітку",
        "lock_biometric_not_configured_warning": "Блокування безпеки екрана не налаштовано на цьому пристрої",
        "action_lock_note": "Заблокувати замітку",
        "action_unlock_note": "Розблокувати замітку",
        "time_travel_menu_title": "Історія замітки",
        "time_travel_title_no_versions": "Історія (Немає попередніх версій)",
        "time_travel_title_version_format": "Історія (Версія %1$d/%2$d)",
        "time_travel_no_history": "Для цієї замітки немає історії",
        "time_travel_btn_cancel": "Скасувати",
        "time_travel_btn_restore": "Відновити",
        "export_menu_clicked": "Натиснуто меню експорту!",
        "export_dialog_title": "Експорт замітки",
        "export_as_pdf": "Експортувати як PDF",
        "export_as_image": "Експортувати як зображення (PNG)",
        "exporting_pdf": "Експорт PDF...",
        "exporting_image": "Експорт зображення...",
        "export_untitled": "Без назви",
        "export_success_format": "Файл створено! Розмір: %1$d байт. Надсилання...",
        "export_share_title": "Поділитися експортованою заміткою",
        "export_failed_format": "Помилка експорту: %1$s"
    }
}

count = 0
for lang_code, keys in translations.items():
    folder_name = f"values-{lang_code}"
    xml_path = os.path.join(res_dir, folder_name, "strings.xml")
    
    if os.path.exists(xml_path):
        with open(xml_path, 'r', encoding='utf-8') as f:
            content = f.read()
            
        updated = False
        block_lines = []
        for key, value in keys.items():
            # Check if key is already in file OR if it is in the file but needs to be added (clean/overwrite checking)
            if f'name="{key}"' not in content:
                # Escape XML chars
                val_escaped = value.replace("'", "\\'").replace("&", "&amp;")
                block_lines.append(f'    <string name="{key}">{val_escaped}</string>')
                updated = True
                
        if updated:
            str_block = "\n    <!-- Features localization keys -->\n" + "\n".join(block_lines) + "\n"
            content = re.sub(r'</resources>', str_block + '</resources>', content)
            
            with open(xml_path, 'w', encoding='utf-8') as f:
                f.write(content)
            count += 1

print(f"Localization added to {count} language files.")
